### ISSUE TITLE
Tests fail with ruby >= 2.1.5

### ISSUE THREAD

**Issue by opoplawski** [mthiede/rgen#24]
Trying to build on Fedora 21 with ruby 2.1.5, tests fail with:
~~~~~
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /usr/share/ruby/test/unit.rb:1:in `<top (required)>'
  rgen_test.rb:3:in `<main>'
MiniTest::Unit::TestCase is now Minitest::Test. From /usr/share/ruby/test/unit/testcase.rb:8:in `<module:Unit>'
/usr/share/ruby/test/unit.rb:676:in `<class:Runner>': undefined method `_run_suite' for class `Test::Unit::Runner' (NameError)
        from /usr/share/ruby/test/unit.rb:261:in `<module:Unit>'
        from /usr/share/ruby/test/unit.rb:15:in `<module:Test>'
        from /usr/share/ruby/test/unit.rb:7:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from rgen_test.rb:3:in `<main>'
~~~~~
With ruby 2..2.1 fails with:
~~~~~
+ ruby rgen_test.rb
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- test/unit (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from test/rgen_test.rb:3:in `<main>'
~~~~~

**Comment by hemalbavisi** [comment]
Is there any update on above issue? I am also facing similar kind of problem with ruby 2.2.0

**Comment by duboviy** [comment]
Try with minitest 4.7.5 version
